kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
      - containerPort: 30081
        hostPort: 8181
      - containerPort: 30082
        hostPort: 8282
      - containerPort: 30083
        hostPort: 8383
