apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
  labels:
    app: registry
    release: gitlab
type: Opaque
stringData:
  config: |
    filesystem:
      rootdirectory: /var/opt/gitlab/registry
